#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (c) 2013 Vincent Batoufflet.
#
# License: BSD, see LICENSE for more details.
#

import argparse
import sys

from plume import __version__
from plume.command import get_modules, load_module

# Get list of available command sub-modules
modules = get_modules()

# Abort if no command found
if not len(modules):
    sys.stderr.write('Abort: could not find any command (please verify your setup and PYTHONPATH).\n')
    sys.exit(1)

# Create arguments parser instance
parser = argparse.ArgumentParser(description='Manage Plume wiki environment.')
parser.add_argument('-D', '--debug', action='store_true', help='enable debug mode')
parser.add_argument('-V', '--version', action='version', version='%(prog)s ' +
    (__version__ if __version__ else '(Development)'), help='show program version and exit')

# Add commands sub-parsers and load sub-modules
subparsers = parser.add_subparsers(metavar='COMMAND')

for name in modules:
    load_module(name)

# Display help by default
if len(sys.argv) == 1:
    sys.argv.append('-h')

# Parse command-line arguments
try:
    args = parser.parse_args()
    args.func(args)
except KeyboardInterrupt:
    pass
except Exception as e:
    if args.debug:
        print('-' * 80)

        import traceback
        traceback.print_exc()

        if hasattr(e, 'errmsg'):
            print('Error: %s' % e.errmsg)

        print('-' * 80)

    sys.stderr.write('Error: %s\n' % e)

# vim: ft=python
